#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'

exe  = Pathname.new(__FILE__).realpath
root = exe.parent.parent
lib  = root.join('app')

ENV['BUNDLE_GEMFILE'] ||= root.join('Gemfile').to_s
require 'bundler/setup'

$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'cli'
CLI.call

